#!/bin/sh

xrandr --output DP-0 --primary --mode 1920x1080 --rotate normal --rate 240 --output DVI-I-1 --right-of DP-0  --mode 1920x1080 --rotate normal --rate 144

bspc monitor DP-0 -d 1 2 
bspc monitor DVI-I-1 -d 3 4

xsetroot -cursor_name left_ptr &
setxkbmap -layout us -variant intl &
xset s off &
bspc desktop 1 -f

sxhkd &
picom &

${HOME}/.config/polybar/launch.sh &
${HOME}/.fehbg &

bspc config border_width         2
bspc config window_gap          8
bspc config normal_border_color "#adb5bd"
bspc config focused_border_color "#e9ecef"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
