#!/bin/sh

xrandr --output DP-0 --primary --mode 1920x1080 --rotate normal --rate 240 --output DVI-I-1 --right-of DP-0  --mode 1920x1080 --rotate normal --rate 144

bspc monitor DP-0 -d I II III 
bspc monitor DVI-I-1 -d IV V X

xsetroot -cursor_name left_ptr &
xset s off

sxhkd &
picom &

${HOME}/.config/polybar/launch.sh &
${HOME}/.fehbg &

bspc config border_width         1
bspc config window_gap          8
bspc config normal_border_color "#adb5bd"
bspc config focused_border_color "#e9ecef"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false

bspc rule -a Chromium desktop=^5
bspc rule -a steam desktop=^1
bspc rule -a OBS studio desktop=^5
